version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      discordjs:
        patterns:
          - discord-api-types
          - "@discordjs/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
